### ISSUE TITLE
Camera preview failed

### ISSUE THREAD

**Issue by Zookey** [ravi8x/Barcode-Reader#4]
I tried to use this library on Samsung Galaxy S5 with Andorid 6.0.1 and I get following error:

` java.lang.RuntimeException: startPreview failed
                                                                                       at android.hardware.Camera.startPreview(Native Method)
                                                                                       at info.androidhive.barcode.camera.CameraSource.start(CameraSource.java:380)
                                                                                       at info.androidhive.barcode.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:91)
                                                                                       at info.androidhive.barcode.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:33)
                                                                                       at info.androidhive.barcode.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:114)
                                                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:712)
                                                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:209)
                                                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
                                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
                                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by nirmal912** [comment]
@Zookey did you set provider?

**Comment by ravi8x** [comment]
As there are no reply from author, closing the issue.
